config/routes.rb
GotEasyData::Application.routes.draw do
  resources :castles
  resources :orders
  resources :houses
  match "houses/get_houses" => "houses#get_houses"
  resources :characters
  root :to => "home#index"

end

app/models/character.rb
class Character < ActiveRecord::Base
  attr_accessible :dob, :email, :is_male, :nickname, :title, :first_name, :last_name, :house_id, :order_id, :father, :mother

  belongs_to :house
  belongs_to :order

  has_many :relationships, :dependent => :destroy
  has_one :father, :through => :relationships
  has_one :mother, :through => :relationships

  def full_name
    "#{first_name} #{last_name}"
  end

  def common_name
    unless nickname.blank?
      "#{first_name} \"#{nickname}\" #{last_name}"
    else
      full_name 
    end
  end

  # ----- relationships -----
  def build_father(father)
    relationships.build(:father => father, :relation_type => 'father')
  end

  def build_mother(mother)
    relationships.build(:mother => father, :relation_type => 'mother')
  end

  scope :children, lambda { |contact| joins (:relationships).\
    where(:relationships => { :relation_type => ['father', 'mother']})}

  def children
    self.class.children(self)
  end

  def siblings
    ((self.father ? self.father.children : []) +
     (self.mother ? self.mother.children : [])
    ).uniq - [self]
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characters }
    end
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = Character.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
    @character = Character.new
    @houses = House.select([:name, :id]).all
    @parent = Character.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
    @houses = House.select([:name, :id]).all
    @parent = Character.all
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(params[:character])

    respond_to do |format|
      if @character.save
        format.html { redirect_to characters_path, success: 'Character was successfully created.' }
        format.json { render json: @character, status: :created, location: @character }
      else
        format.html { render action: "new" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = Character.find(params[:id])
    @father = Character.find(params[:relationship][:character_id])

    unless @father.blank?
      @character.build_father(@father)
=begin
      relationship = Relationship.new
      relationship.relation_id = @father.id
      relationship.character_id = @character.id
      relationship.relation_type = 'father'
      relationship.save
=end
      flash[:info] = @character.father.inspect 
    end


    respond_to do |format|
      if @character.update_attributes(params[:character])
        format.html { redirect_to @character, success: 'Character was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character, :html => { class:""}) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :nickname %>
    <%= f.text_field :nickname, placeholder: "e.g. \"Kingslayer\""   %>
  </div>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, placeholder: "e.g. \"Lord of Winterfell\"" %>
  </div>
  <div class="field">
    Date of Birth (estimated)<br/><%= f.date_select :dob %>
  </div>
  <div class="field">
    <%= f.label :is_male %>
    <%= f.select :is_male, [['Male',1], ['Female',0]] %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :house %>
    <%= f.collection_select :house_id, @houses, :id, :name, prompt: "Select a House" %>
    <%= link_to "Add a house", "#add_house_modal", remote: url_for(House.new), role: "button", class: "btn", :'data-toggle'=>"modal" %> 
  </div>
  <div class="field">
    <%= f.collection_select :order_id, Order.all, :id, :name, prompt: "None" %>
    &nbsp;What order does this character belong to?
  </div>
  <div class="field">
      <%= collection_select :relationship, :character_id, @parent, :id, :full_name %>
    &nbsp;Father
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
<%= render "houses/modal" %>

<script type="text/javascript">
  FocusFormsFirstInput('new_character'); 
</script>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table class="table table-striped sortable">
  <tr>
    <th><i class="icon-user"></i>&nbsp;Name</th>
    <th><i class="icon-certificate"></i>&nbsp;Title</th>
    <th><i class="icon-asterisk"></i>&nbsp;Nickname</th>
    <th><i class="icon-home"></i>&nbsp;House</th>
    <th><i class="icon-cog"></i>&nbsp;Order</th>
    <th></th>
  </tr>
  <% @characters.each do |character| %>
    <tr>
    <td><%= link_to character.full_name, character %></td>
    <td><%= character.title %></td>
    <td><%= character.nickname %></td>
    <td><%= link_to(character.house.name, character.house) unless character.house.blank? %></td>
    <td><%= link_to(character.order.name, character.order) unless character.order.blank? %></td>
    <td style="width:78px;">
      <%= link_to raw('<i class="icon-pencil"></i>'), edit_character_path(character), class: 'btn btn-small pull-left' %>
      <%= link_to raw('<i class="icon-remove"></i>'), character, class: 'btn btn-small close pull-left', method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to new_character_path, class: "btn btn-primary" do %>
  <i class="icon-plus icon-white"></i>
New Character
<% end %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<h2><%= @character.common_name %></h2>
<h4><%= @character.title %></h4>
<p>
  <b>Dob:</b>
  <%= @character.dob %>
</p>

<p>
  <b>Is male:</b>
  <%= @character.is_male %>
</p>

<p>
  <b>Email:</b>
  <%= @character.email %>
</p>

<p>
  <b>Nickname:</b>
  <%= @character.nickname %>
</p>

<p>
  <b>House</b>
  <%= link_to @character.house.name, @character.house %>
</p>

<p>
  <b>Father</b>
  <%= @character.inspect%>
  <br/><hr/>
  <% Relationship.all do |r| %>
 <%= r %>
  <% end %>
</p>


<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>