config/routes.rb
GotEasyData::Application.routes.draw do
  resources :castles
  resources :orders
  resources :houses
  match "houses/get_houses" => "houses#get_houses"
  resources :characters
  root :to => "home#index"

end

app/models/castle.rb
class Castle < ActiveRecord::Base
  attr_accessible :name, :ruined

  has_one :house
end

app/controllers/castles_controller.rb
class CastlesController < ApplicationController
  # GET /castles
  # GET /castles.json
  def index
    @castles = Castle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @castles.to_json }
    end
  end

  # GET /castles/1
  # GET /castles/1.json
  def show
    @castle = Castle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @castle }
    end
  end

  # GET /castles/new
  # GET /castles/new.json
  def new
    @castle = Castle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @castle }
    end
  end

  # GET /castles/1/edit
  def edit
    @castle = Castle.find(params[:id])
  end

  # POST /castles
  # POST /castles.json
  def create
    @castle = Castle.new(params[:castle])

    respond_to do |format|
      if @castle.save
        format.html { redirect_to castles_path, success: 'Castle was successfully created.' }
        format.json { render json: @castle, status: :created, location: @castle }
      else
        format.html { render action: "new" }
        format.json { render json: @castle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /castles/1
  # PUT /castles/1.json
  def update
    @castle = Castle.find(params[:id])

    respond_to do |format|
      if @castle.update_attributes(params[:castle])
        format.html { redirect_to @castle, success: 'Castle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @castle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /castles/1
  # DELETE /castles/1.json
  def destroy
    @castle = Castle.find(params[:id])
    @castle.destroy

    respond_to do |format|
      format.html { redirect_to castles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/castles_helper.rb
module CastlesHelper
end

app/views/castles/_form.html.erb
<%= form_for(@castle) do |f| %>
  <% if @castle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@castle.errors.count, "error") %> prohibited this castle from being saved:</h2>

      <ul>
      <% @castle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    Ruined? <%= f.check_box :ruined %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/castles/_modal.html.erb
<!-- Modal -->
<div id="add_castle_modal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Add Castle</h3>
  </div>
  <div class="modal-body">
    <% @castle = Castle.new %>
    <%= form_for(@castle, remote: true) do |f| %>
      <% if @castle.errors.any? %>
      <div id="error_explanation">
      <h2><%= pluralize(@castle.errors.count, "error") %> prohibited this castle from being saved:</h2>

      <ul>
        <% @castle.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <div class="field">
      Ruined? <%= f.check_box :ruined %>
    </div>
  <% end %>  
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Create House</button>
  </div>
</div>

app/views/castles/edit.html.erb
<h1>Editing castle</h1>

<%= render 'form' %>

<%= link_to 'Show', @castle %> |
<%= link_to 'Back', castles_path %>

app/views/castles/index.html.erb
<h1>Listing castles</h1>
<%= link_to 'New Castle', new_castle_path, class: 'btn btn-primary pull-left' %>

<table class="table table-striped sortable">
  <tr>
    <th>Name</th>
    <th>Seated By</th>
    <th>Ruined</th>
    <th></th>
  </tr>

<% @castles.each do |castle| %>
  <tr>
    <td><%= link_to castle.name, castle %></td>
    <td><%= link_to castle.house.name, castle.house unless castle.house.blank? %></td>
    <td><%= castle.ruined ? "Yes" : "No" %></td>
    <td><%= link_to 'Edit', edit_castle_path(castle) %></td>
    <td><%= link_to 'Destroy', castle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Castle', new_castle_path, class: 'btn btn-primary' %>

app/views/castles/new.html.erb
<h1>New castle</h1>

<%= render 'form' %>

<%= link_to 'Back', castles_path %>

app/views/castles/show.html.erb
<h2><%= @castle.name %></h2>
<p>Ruined: <%= @castle.ruined %></p>
<% unless @castle.house.blank? %>
  Seated by: <%= link_to @castle.house.name, @castle.house %>
<% end %>

<div>
<%= link_to 'Edit', edit_castle_path(@castle) %> |
<%= link_to 'Back', castles_path %>
</div>