config/routes.rb
GotEasyData::Application.routes.draw do
  resources :castles
  resources :orders
  resources :houses
  match "houses/get_houses" => "houses#get_houses"
  resources :characters
  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GotEasyData</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <%= link_to "got_easy_data", root_path, class: "brand" %>
    <ul class="nav">
      <li class="divider-vertical"></li>
      <li><%= link_to "Characters", characters_path %></li>
      <li><%= link_to "Houses", houses_path %></li>
      <li><%= link_to "Orders", orders_path %></li>
      <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Places<b class="caret"></b></a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
            <li><%= link_to "Castles", castles_path %></li>
            <li><%= link_to "Cities", "#"%></li>
            <li><%= link_to "Towns", "#"%></li>
            <li><%= link_to "Septries", "#"%></li>
          </ul>
      </li>
    </ul>
  </div>
</div>
<div class="container-fluid">
  <div class="row-fluid">
    <!--
    <div class="span2 sidebar-links">
      <ul>
        <li>Characters</li>
        <li>Houses</li>
      </ul>
    </div>
-->
    <div class="span12">
      <%= render_flash_messages %>
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>